### ISSUE TITLE
20231004 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [wegoedod/C202309#1]
에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week5/functionMulti
    - Error: conflicting types for 'multif' [line 11]
        - 이유: 함수 원형과 선언부에 반환 자료형이 맞지 않습니다
        - 해결: 반환 자료형을 동일하게 맞춰주세요 (예: 원형 부분 int 반환형을 long으로 변경)

워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: return type of 'main' is not 'int' [line 5]
- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 5]
    
- 이유: main의 반환값은 int 여야 합니다
- 해결: void main()을 int main()으로 변경하고 마지막에 return 0;을 추가하세요.

**Comment by MisooKim2** [comment]
제가 수업시간에 void main() 함수에 대해 알려드렸었는데,
최근 컴파일러들이 해당 코드를 지양하는 추세라고 합니다.
하여 워닝 메세지에 추가되었으니 수정부탁드립니다.
관련하여 수업시간에 추가 공지하도록 하겠습니다.

**Comment by wegoedod** [comment]
challenge/week5/functionMulti과 practice/week5/functionHap의 main함수 반환 자료형 int로 변경했고 functionMulti에서 multif 자료 반환형 변경했습니다.
