### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [wegoedod/C202309#2]
### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week5/functionMulti
    - Error: conflicting types for 'multif' [line 12]
        -  위 함수에서 원형선언한 부분과 함수 정의한 곳에 반환형이 다릅니다. 하나로 맞춰주세요. 

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week5/functionMulti
    - Warning: format specifies type 'long' but the argument has type 'int' [line 6]
    - Warning: format specifies type 'long' but the argument has type 'int' [line 7]
    - Warning: format specifies type 'long' but the argument has type 'int' [line 8]
       - 서식 지정자를 맞춰주세요.

**Comment by wegoedod** [comment]
#2 week5 functionMulti에서 프린트문의 서식지정자를 long로 통일했고 multif함수 원형 선언한 곳과 정의한 부분에서 반환형을 long로 통일했습니다
